In [1]:
import numpy as np

In [98]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])


In [152]:
arr = np.arange(24).reshape((2, 3, 4))

In [153]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [154]:
 arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [155]:
arr.T

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [148]:
arr=np.arange(24).reshape(3,4,2)

In [149]:
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [150]:
arr.T

array([[[ 0,  8, 16],
        [ 2, 10, 18],
        [ 4, 12, 20],
        [ 6, 14, 22]],

       [[ 1,  9, 17],
        [ 3, 11, 19],
        [ 5, 13, 21],
        [ 7, 15, 23]]])

In [151]:
arr3d 

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [100]:
old_values = arr3d[0].copy()

In [101]:
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [102]:
arr3d[0] = 42


In [103]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [110]:
arr3d[:,:,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [111]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])


In [112]:
data = np.random.randn(7, 4)

In [113]:
data

array([[-5.01591522e-01,  1.10169989e-03,  2.21873873e+00,
        -8.78525687e-01],
       [-1.02000307e+00,  6.53220784e-01, -4.93335905e-01,
         7.37095818e-01],
       [ 9.09515151e-02,  1.47500394e+00, -1.96289953e+00,
         1.12126331e+00],
       [ 1.26759571e+00,  1.84793823e-01, -4.37731126e-01,
         2.08647654e-01],
       [ 1.41446785e-01,  7.67614626e-01,  1.25229688e+00,
        -1.04577167e+00],
       [ 5.26098578e-01,  1.61402924e-01, -3.21551522e-02,
         1.52378144e-01],
       [-7.52033840e-01, -2.16312777e-01, -1.60476064e+00,
        -3.68027733e-01]])

In [126]:
 data[[2,0,3]]

array([[ 9.09515151e-02,  1.47500394e+00, -1.96289953e+00,
         1.12126331e+00],
       [-5.01591522e-01,  1.10169989e-03,  2.21873873e+00,
        -8.78525687e-01],
       [ 1.26759571e+00,  1.84793823e-01, -4.37731126e-01,
         2.08647654e-01]])

In [127]:
arr = np.arange(32).reshape((8, 4))

In [128]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [156]:
np.sqrt(arr)

array([[[0.        , 1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974, 2.64575131],
        [2.82842712, 3.        , 3.16227766, 3.31662479]],

       [[3.46410162, 3.60555128, 3.74165739, 3.87298335],
        [4.        , 4.12310563, 4.24264069, 4.35889894],
        [4.47213595, 4.58257569, 4.69041576, 4.79583152]]])

In [157]:
np.square(arr)

array([[[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121]],

       [[144, 169, 196, 225],
        [256, 289, 324, 361],
        [400, 441, 484, 529]]], dtype=int32)

In [158]:
np.abs(arr)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [162]:
arrr=np.random.randn(24).reshape(2,3,4)

In [164]:
arrr

array([[[-0.75228826, -0.45035185, -0.71889356,  2.47250679],
        [-0.48780162,  1.88401026,  1.69210767,  0.10445711],
        [-0.41020108, -1.79900273, -2.37258628, -1.48325459]],

       [[-1.21282559, -0.37088453,  2.13299708, -1.29449932],
        [-2.17004845,  0.14886842, -0.78914371,  0.24588356],
        [ 0.90357843,  0.15073355, -0.2666359 ,  0.1845193 ]]])

In [166]:
np.fabs(arrr)

array([[[0.75228826, 0.45035185, 0.71889356, 2.47250679],
        [0.48780162, 1.88401026, 1.69210767, 0.10445711],
        [0.41020108, 1.79900273, 2.37258628, 1.48325459]],

       [[1.21282559, 0.37088453, 2.13299708, 1.29449932],
        [2.17004845, 0.14886842, 0.78914371, 0.24588356],
        [0.90357843, 0.15073355, 0.2666359 , 0.1845193 ]]])

In [172]:
np.sign(arrr)

array([[[-1., -1., -1.,  1.],
        [-1.,  1.,  1.,  1.],
        [-1., -1., -1., -1.]],

       [[-1., -1.,  1., -1.],
        [-1.,  1., -1.,  1.],
        [ 1.,  1., -1.,  1.]]])

In [173]:
np.ceil(arrr)

array([[[-0., -0., -0.,  3.],
        [-0.,  2.,  2.,  1.],
        [-0., -1., -2., -1.]],

       [[-1., -0.,  3., -1.],
        [-2.,  1., -0.,  1.],
        [ 1.,  1., -0.,  1.]]])

In [174]:
np.floor(arrr)

array([[[-1., -1., -1.,  2.],
        [-1.,  1.,  1.,  0.],
        [-1., -2., -3., -2.]],

       [[-2., -1.,  2., -2.],
        [-3.,  0., -1.,  0.],
        [ 0.,  0., -1.,  0.]]])

In [175]:
np.rint(arrr)

array([[[-1., -0., -1.,  2.],
        [-0.,  2.,  2.,  0.],
        [-0., -2., -2., -1.]],

       [[-1., -0.,  2., -1.],
        [-2.,  0., -1.,  0.],
        [ 1.,  0., -0.,  0.]]])

In [176]:
np.modf(arrr)

(array([[[-0.75228826, -0.45035185, -0.71889356,  0.47250679],
         [-0.48780162,  0.88401026,  0.69210767,  0.10445711],
         [-0.41020108, -0.79900273, -0.37258628, -0.48325459]],
 
        [[-0.21282559, -0.37088453,  0.13299708, -0.29449932],
         [-0.17004845,  0.14886842, -0.78914371,  0.24588356],
         [ 0.90357843,  0.15073355, -0.2666359 ,  0.1845193 ]]]),
 array([[[-0., -0., -0.,  2.],
         [-0.,  1.,  1.,  0.],
         [-0., -1., -2., -1.]],
 
        [[-1., -0.,  2., -1.],
         [-2.,  0., -0.,  0.],
         [ 0.,  0., -0.,  0.]]]))

In [177]:
arr<arrr

array([[[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]],

       [[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]]])

In [167]:
np.log(arr)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[[      -inf, 0.        , 0.69314718, 1.09861229],
        [1.38629436, 1.60943791, 1.79175947, 1.94591015],
        [2.07944154, 2.19722458, 2.30258509, 2.39789527]],

       [[2.48490665, 2.56494936, 2.63905733, 2.7080502 ],
        [2.77258872, 2.83321334, 2.89037176, 2.94443898],
        [2.99573227, 3.04452244, 3.09104245, 3.13549422]]])

In [168]:
arr+4

array([[[ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27]]])

In [171]:
np.log2(arr)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log2
  """Entry point for launching an IPython kernel.


array([[[      -inf, 0.        , 1.        , 1.5849625 ],
        [2.        , 2.32192809, 2.5849625 , 2.80735492],
        [3.        , 3.169925  , 3.32192809, 3.45943162]],

       [[3.5849625 , 3.70043972, 3.80735492, 3.9068906 ],
        [4.        , 4.08746284, 4.169925  , 4.24792751],
        [4.32192809, 4.39231742, 4.45943162, 4.52356196]]])

In [133]:
arr[[1, 5, 7, 2]][:,[0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [ ]:
arr[[1, 5, 7, 2]][:,[0, 3, 1, 2]]

In [114]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [115]:
 data[names == 'Bob']

array([[-5.01591522e-01,  1.10169989e-03,  2.21873873e+00,
        -8.78525687e-01],
       [ 1.26759571e+00,  1.84793823e-01, -4.37731126e-01,
         2.08647654e-01]])

In [116]:
data[names == 'Bob', 2:]

array([[ 2.21873873, -0.87852569],
       [-0.43773113,  0.20864765]])

In [117]:
 data[names == 'Bob', 3]

array([-0.87852569,  0.20864765])

In [118]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [119]:
 data[~(names == 'Bob')]

array([[-1.02000307,  0.65322078, -0.4933359 ,  0.73709582],
       [ 0.09095152,  1.47500394, -1.96289953,  1.12126331],
       [ 0.14144679,  0.76761463,  1.25229688, -1.04577167],
       [ 0.52609858,  0.16140292, -0.03215515,  0.15237814],
       [-0.75203384, -0.21631278, -1.60476064, -0.36802773]])

In [125]:
 data[[2,0,3]]

array([[ 9.09515151e-02,  1.47500394e+00, -1.96289953e+00,
         1.12126331e+00],
       [-5.01591522e-01,  1.10169989e-03,  2.21873873e+00,
        -8.78525687e-01],
       [ 1.26759571e+00,  1.84793823e-01, -4.37731126e-01,
         2.08647654e-01]])

In [120]:
cond=names == 'Bob'

In [121]:
cond

array([ True, False, False,  True, False, False, False])

In [122]:
 data[~cond]

array([[-1.02000307,  0.65322078, -0.4933359 ,  0.73709582],
       [ 0.09095152,  1.47500394, -1.96289953,  1.12126331],
       [ 0.14144679,  0.76761463,  1.25229688, -1.04577167],
       [ 0.52609858,  0.16140292, -0.03215515,  0.15237814],
       [-0.75203384, -0.21631278, -1.60476064, -0.36802773]])

In [123]:
mask = (names == 'Bob') | (names == 'Will')


In [124]:
 data[mask]

array([[-5.01591522e-01,  1.10169989e-03,  2.21873873e+00,
        -8.78525687e-01],
       [ 9.09515151e-02,  1.47500394e+00, -1.96289953e+00,
         1.12126331e+00],
       [ 1.26759571e+00,  1.84793823e-01, -4.37731126e-01,
         2.08647654e-01],
       [ 1.41446785e-01,  7.67614626e-01,  1.25229688e+00,
        -1.04577167e+00]])

In [105]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [2]:
data = np.random.randn(2, 3)

In [3]:
data

array([[ 1.12846473, -0.31844018,  0.80011974],
       [-1.04421421, -0.4211011 , -0.06979858]])

In [4]:
data*10

array([[ 11.28464728,  -3.18440175,   8.00119742],
       [-10.44214207,  -4.21101105,  -0.69798581]])

In [5]:
data+data

array([[ 2.25692946, -0.63688035,  1.60023948],
       [-2.08842841, -0.84220221, -0.13959716]])

In [15]:
data1=np.array([6,7.5,8,0,1])

In [16]:
data1.shape

(5,)

In [29]:
data1.ndim

1

In [30]:
data1.dtype

dtype('float64')

In [31]:
data1.astype('f4')

array([6. , 7.5, 8. , 0. , 1. ], dtype=float32)

In [33]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
np.empty((2, 3, 2))

array([[[7.75149782e-312, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 5.49275720e+170]],

       [[4.00674187e+174, 1.17363148e+165],
        [9.59935831e-071, 4.18678276e-062],
        [1.64759396e+185, 8.98063799e-067]]])

In [23]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
np.zeros_like(data)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [37]:
arr = np.array([1, 2, 3, 4, 5])

In [38]:
arr.dtype

dtype('int32')

In [42]:
float_arr=arr.astype(np.float64)

In [41]:
arr.dtype

dtype('int32')

In [44]:
float_arr.dtype

dtype('float64')

In [45]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [50]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [48]:
arr1

array([ 3, -1, -2,  0, 12, 10])

In [51]:
arr.dtype

dtype('float64')

In [52]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)


In [53]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [58]:
empty_uint32 = np.empty(8, dtype=np.int32)


In [59]:
empty_uint32.dtype

dtype('int32')

In [63]:
int_array = np.arange(10)

In [64]:
int_array.dtype

dtype('int32')

In [61]:
int_array.astype(empty_uint32.dtype)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
int_array.dtype

dtype('int32')

In [65]:
 arr = np.array([[1., 2., 3.], [4., 5., 6.]])


In [66]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [67]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])


In [68]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [69]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
arr3d[0,0]

array([1, 2, 3])

In [72]:
arr3d[0,0,2]

3

In [73]:
arr3d[0,0]=0

In [74]:
arr3d

array([[[ 0,  0,  0],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [75]:
arr = np.random.randn(6, 3)


In [76]:
arr

array([[-1.06031861,  0.53529717,  0.87800064],
       [-0.22060752,  0.48287203,  0.4018633 ],
       [ 0.70139868,  0.26192599, -0.20474412],
       [ 1.07433012, -0.05949827,  1.29397666],
       [-1.62603843, -0.30929221,  0.775683  ],
       [-0.15765336, -0.66071292,  0.5842485 ]])

In [78]:
arr.T

array([[-1.06031861, -0.22060752,  0.70139868,  1.07433012, -1.62603843,
        -0.15765336],
       [ 0.53529717,  0.48287203,  0.26192599, -0.05949827, -0.30929221,
        -0.66071292],
       [ 0.87800064,  0.4018633 , -0.20474412,  1.29397666,  0.775683  ,
         0.5842485 ]])

In [77]:
np.dot(arr.T, arr)

array([[ 5.48794408,  0.05276764, -1.12646274],
       [ 0.05276764,  1.12405696, -0.09251062],
       [-1.12646274, -0.09251062,  3.59170541]])

In [79]:
arr = np.arange(16).reshape((2, 2, 4))

In [80]:
arr 

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [81]:
arr = np.arange(10)

In [82]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [86]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [87]:
x = np.random.randn(8)

In [88]:
y = np.random.randn(8)


In [90]:
np.maximum(x,y)

array([1.23602318, 0.50366405, 0.22394768, 1.46328819, 0.44026871,
       0.42435276, 0.95599972, 1.72773717])

In [93]:
np.random.randn(5,3)

array([[-2.43153916, -0.01156205,  0.49624523],
       [ 0.63492532, -1.56947171, -1.56198411],
       [ 0.19459596,  1.28721784,  0.62384373],
       [-0.95990701,  0.0449744 ,  0.65849044],
       [-1.06523268,  0.47221208,  1.62309976]])

In [95]:
np.random.randn?

In [1]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!
